name: artiboost
channels:
  - pytorch
  - nvidia
  - conda-forge
  - fvcore
  - defaults
dependencies:
  - python=3.8
  - pytorch==1.9.0
  - cudatoolkit==11.1.1
  - torchvision
  - ipython
  - cython
  - pyembree
  - fvcore
  - pip
  - setuptools
